[build-system]
# Please do not change any information given here.
requires = ["setuptools", "setuptools-scm"] 
build-backend = "setuptools.build_meta"

[project] 
name = "pymodulepackage" # insert name of the package (all lowercase, without underscores or special characters)
version = "2.0.1" # insert version of package
description = "This package contains standardized functions for UNICADO module execution." # Insert short package description
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [ # Insert name of author(s)
    {name = "A. Gobbin", email = "a.gobbin@tu-berlin.de"},
    {name = "S. Roscher", email = "s.roscher@tu-berlin.de"}
]

[project.urls]
homepage = "https://unicado.ilr.rwth-aachen.de/"
repository = "https://git.rwth-aachen.de/unicado"
