/*
 * UNICADO - UNIversity Conceptual Aircraft Design and Optimization
 *
 * Copyright (C) 2025 UNICADO consortium
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Description:
 * This file is part of UNICADO.
 */

#include <pybind11/pybind11.h>
#include <pybind11/operators.h>
#include <pybind11/stl.h>
#include <pybind11/stl/filesystem.h>
#include <memory>
#include "aerodynamics/aerodynamics_v2.h"

/* === Python bindings === */
namespace py = pybind11;
using namespace aerodynamics;

// generated by CHATGPT
PYBIND11_MODULE(pyaerodynamics, m) {
    m.doc() = "Aerodynamics module exposing Aircraft class";

    py::class_<Flight_Condition>(m, "Flight_Condition")
        // === Constructors ===
        // Flight_Condition(double altitude, double freestream_M)
        .def(py::init<const double, const double>(),
            py::arg("altitude"), py::arg("freestream_M"),
            "Construct using altitude (m) and freestream Mach number.")

        // Flight_Condition(double u, double v, double w, double p, double q, double r, double altitude)
        .def(py::init<const double, const double, const double,
            const double, const double, const double, const double>(),
            py::arg("u"), py::arg("v"), py::arg("w"),
            py::arg("p"), py::arg("q"), py::arg("r"),
            py::arg("altitude"),
            "Construct using velocity components, angular rates, and altitude.")

        // Flight_Condition(double freestream_M, double RE, double characteristic_length)
        .def(py::init<const double, const double, const double>(),
            py::arg("freestream_M"), py::arg("RE"), py::arg("characteristic_length"),
            "Construct using Mach number, Reynolds number, and reference length.")

        // === Attributes ===
        .def_readwrite("altitude", &Flight_Condition::altitude)
        .def_readwrite("freestream_M", &Flight_Condition::freestream_M)
        .def_readwrite("density", &Flight_Condition::density)
        .def_readwrite("RE", &Flight_Condition::RE)
        .def_readwrite("p", &Flight_Condition::p)
        .def_readwrite("q", &Flight_Condition::q)
        .def_readwrite("r", &Flight_Condition::r)
        .def_readwrite("u", &Flight_Condition::u)
        .def_readwrite("v", &Flight_Condition::v)
        .def_readwrite("w", &Flight_Condition::w)

        // === Methods ===
        .def("calculate_RE", &Flight_Condition::calculate_RE,
            py::arg("freestream_M"), py::arg("altitude"), py::arg("characteristic_length"),
            "Compute the Reynolds number given Mach, altitude, and characteristic length.");

    // Expose nested struct first
    py::class_<Aircraft::trim_settings>(m, "TrimSettings")
        .def(py::init<>())
        .def_readwrite("method", &Aircraft::trim_settings::method)
        .def_readwrite("reference_wing_ID", &Aircraft::trim_settings::reference_wing_ID)
        .def_readwrite("adjustable_surface_ID", &Aircraft::trim_settings::adjustable_surface_ID)
        .def_readwrite("reference_wing_angle", &Aircraft::trim_settings::reference_wing_angle)
        .def_readwrite("adjustable_surface_angle", &Aircraft::trim_settings::adjustable_surface_angle);

    // Expose Aircraft
    py::class_<Aircraft, std::shared_ptr<Aircraft>>(m, "Aircraft")
        .def(py::init<const std::string&>(), py::arg("path_polarXML"), "Create an Aircraft object from a polar XML file path")
        .def("change_settings", &Aircraft::change_settings,
            py::arg("reference_wing_ID"),
            py::arg("adjustable_surface_ID"),
            py::arg("method"))
        .def("linearized_trim", &Aircraft::linearized_trim,
            py::arg("conditions"), py::arg("weight"), py::arg("cog_position"))
        .def("get_CL", &Aircraft::get_CL,
            py::arg("conditions"), py::arg("weight"))
        .def("get_CD", &Aircraft::get_CD,
            py::arg("conditions"), py::arg("weight"))
        .def("get_CL_CD", &Aircraft::get_CL_CD,
            py::arg("conditions"), py::arg("weight"), py::arg("cog_position"))
        .def_readwrite("polarXML", &Aircraft::polarXML)
        .def_readwrite("components", &Aircraft::components)
        .def_readwrite("settings", &Aircraft::settings);
}
